sonar.projectKey=fastapi-jwt-auth-mongodb
sonar.projectName=FastAPI JWT Auth MongoDB
sonar.projectVersion=1.0
sonar.sources=.
sonar.sourceEncoding=UTF-8
sonar.host.url=http://localhost:9000
sonar.login=squ_3ee6521d66e42d6e290fa9a7a46aff9e7f9bbb39
# Important : précision d'analyse Python
sonar.python.version=3.13.5